### ISSUE TITLE
zeitline-react : Release Patch 0.0.2 won't build

### ISSUE THREAD

**Issue by froger** [octree-gva/Zeitline#6]
A release done yesterday won't build, because of a depedency that don't exists. 

```
[x ] bug report (please search on github for a similar issue before submiting)
[ ] feature request
[ ] support request
```

**Current behavior**
Travis build fails, and basic "clone & npm install" fails

**Expected behavior**
Push rejected, as build can't be done

**Minimal reproduction of the problem with instructions**
`npm install && lerna bootstrap` fails.

 * **D3 timeline version:** 0.0.2
 * **Browser and environment:** any

**Comment by BafS** [comment]
This issue is now fixed
