### ISSUE TITLE
Drag'n Drop won't work if there is no data.

### ISSUE THREAD

**Issue by froger** [octree-gva/Zeitline#7]
**I'm submitting a ...**  
```
[ x] bug report (please search on github for a similar issue before submiting)
[ ] feature request
[ ] support request
```

**Current behavior**
[Code pen](https://codepen.io/doublecompil/pen/eRjVge)
I have set 2 intervals and puts 2 data. I want to drag the intervals to check if my points are in the same place or not. All the intervals in the middle won't drag.

**Expected behavior**
Even I have no data in a interval, I can still drag intervals.

**Minimal reproduction of the problem with instructions**
See the [Code pen](https://codepen.io/doublecompil/pen/eRjVge)

 * **D3 timeline version:** 0.0.2
 * **Browser and environment:** Firefox 54.0.1, Mac OSX 10.11.6

**Comment by BafS** [comment]
The problem was overlapping intervals, an exception is now thrown if an overlap is detected.
